project:
  type: website

website:
  title: "E80 SP24"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: lectures/
        text: Lectures
      - text: Labs
        menu:
        - href: labs/lab_overview
          text: Lab Overview
        - href: labs/lab0
          text: 'Lab 0: Tutorial & Skills Review'
        - href: labs/lab1
          text: 'Lab 1: Go Autonomous'
        - href: labs/lab2
          text: 'Lab 2: BEM'
        - href: labs/lab3
          text: 'Lab 3: Op-Amps'
        - href: labs/lab4
          text: 'Lab 4: Temperature'
        - href: labs/lab5
          text: 'Lab 5: Acoustics'
        - href: labs/lab6
          text: 'Lab 6: Fluids'
        - href: labs/lab7
          text: 'Lab 7: Navigation'
      - href: project/
        text: Project
      - href: reference/
        text: Reference Designs
      - href: history/
        text: History
    right:
      - icon: github
        href: https://github.com/HMC-E80/E80
        aria-label: GitHub

format:
  html:
    theme: [cosmo, custom.scss]
    toc: true

execute:
  freeze: auto


